### PR TITLE
Upgrade packages separately in serial execution

### PR DESCRIPTION
**Pull request by addisonElliott**
In the current code, with serial execution, it runs the following single command.
```
pip install --upgrade <ALL_PACKAGES_HERE>
```

Although this speeds things up by not calling multiple commands, the drawback (as I learned the hard way), is that if **one package has a problem, then the entire command will fail and no packages will be installed**.

Here is a screenshot demonstrating my point. Certifi causes issues and so sympy never gets upgraded because pip exits after the first error.
Screenshot

This PR addresses that by calling the pip upgrade command for each package, so that if one has an issue, it does not effect the other installations. Although this may take longer (this is just me guessing), I think it is worth the wait.

As a side effect, after each package is installed, the output from the command is displayed on the screen. As a first time user of your Python module, I was confused when I did not see any text on the command prompt until it was finished.

This PR also includes other minor fixes such as syntax issues that were causing PEP8 warnings. Let me know if you want me to revert any of those changes!

I saw in response to an issue that you haven't accepted a PR before. I've done quite a few on other Python projects, so feel free to bug me if you have issues.

### CODE REVIEW

**Comment by addisonElliott** [comment]
@defjaf I reread your response and understood what you meant by "serial execution".

I implemented the options --sequential_run and --batch_run that run pip sequentially or all at once. Hope this helps out, feel free to clean/change anything up.

**Comment by addisonElliott** [comment]
@defjaf Fixed merged conflicts here.

**Comment by addisonElliott** [comment]
@defjaf Bump. When you get some free time, can you take a look at this please?

**Comment by defjaf** [comment]
>@defjaf Bump. When you get some free time, can you take a look at this please?

@addisonElliott ok — but terrible connectivity until after New Year’s!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by addisonElliott** [comment]
@defjaf No problem, just a friendly reminder. I know how easy it can be to forget about PRs.

**Comment by addisonElliott** [comment]
Sorry to keep bugging you but wanted to remind you again. I will be using this package in the coming weeks and may need this functionality.

**Comment by defjaf** [comment]
OK, going to get to this today or tomorrow I hope. I think I am going to rename the options (still considering it) and possibly clean up the interaction with serial/parallel since the two sets of options duplicate some functionality and is slightly confusing (as evidenced by our own discussion earlier)! Sorry this is taking so long...

**Comment by defjaf** [comment]
OK, done. It's now a mutually exclusive `argparse` group of `--parallel`/`--serial`/`--sequential` which seems to cover all the possibilities in a less verbose manner. I've left `--serial` (which is now the same as your `--serial --batch`) as the default (which I still prefer, sorry!). It seems to work here, but please test and if there are no problems I'll push to pypy.

**Comment by addisonElliott** [comment]
@defjaf Perfect, I just tested the sequential run and it worked perfectly. I understand the default being `--serial`, I think it makes the most sense actually. It is nice to have options when the user needs more fine control!

**Pull request merged**
